# Forge
forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/apache',    '0.11.0'
mod 'puppetlabs/firewall',  '1.0.0'
mod 'puppetlabs/inifile',   '1.0.1'
mod 'puppetlabs/java',      '1.0.1'
mod 'puppetlabs/mysql',     '2.2.0'
mod 'puppetlabs/passenger', '0.2.0'
mod 'puppetlabs/postgresql', '3.3.0'
mod 'puppetlabs/puppetdb',   '3.0.1'
mod 'puppetlabs/ruby',       '0.1.0'
mod 'puppetlabs/stdlib',     '4.1.0'

mod 'fsalum/puppetmaster',   '0.0.4'

# Github
#:cachedir: '/var/cache/r10k'
